---

- name: "{{ project_name }} "
    ec2_group:
        profile: "{{ aws_profile }}"
        name: "{{ aws_security}}"
        purge_rules: true
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_settings['vpc_id'] }}"
        rules:
            - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: "0.0.0.0/0"
            
- name: Setup security key (SSH key)
  ec2_key:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    name: "{{ aws_ssh_key_name }}"
    key_material: "{{ item }}"
  with_file: "ssh/serveraws.pem"